# Generated by Django 5.0.6 on 2024-05-22 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CensusSuportToolBackendAplication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityAdmin',
            fields=[
                ('AdminId', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.RemoveField(
            model_name='censustemplate',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='censusrecord',
            name='census_template',
        ),
        migrations.RemoveField(
            model_name='censusrecord',
            name='community',
        ),
        migrations.RemoveField(
            model_name='censusrecord',
            name='volunteer',
        ),
        migrations.RemoveField(
            model_name='censusresponse',
            name='record',
        ),
        migrations.RemoveField(
            model_name='censusresponse',
            name='question',
        ),
        migrations.RemoveField(
            model_name='censustemplate',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='permissionrequest',
            name='census_template',
        ),
        migrations.RemoveField(
            model_name='permissionrequest',
            name='community',
        ),
        migrations.RemoveField(
            model_name='permissionrequest',
            name='volunteer',
        ),
        migrations.RemoveField(
            model_name='report',
            name='community',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='community',
            name='address',
        ),
        migrations.RemoveField(
            model_name='community',
            name='administrators',
        ),
        migrations.RemoveField(
            model_name='community',
            name='id',
        ),
        migrations.RemoveField(
            model_name='community',
            name='name',
        ),
        migrations.RemoveField(
            model_name='question',
            name='text',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='community',
            name='CommunityId',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='question',
            name='hint',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('numeric', 'Numeric'), ('text', 'Text'), ('date', 'Date'), ('boolean', 'Boolean')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='community',
            name='AdminId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CensusSuportToolBackendAplication.communityadmin'),
        ),
        migrations.AddField(
            model_name='question',
            name='form',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CensusSuportToolBackendAplication.form'),
        ),
        migrations.CreateModel(
            name='MemberSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CommunityId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CensusSuportToolBackendAplication.community')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('numeric', 'Numeric'), ('text', 'Text'), ('date', 'Date'), ('boolean', 'Boolean')], max_length=10)),
                ('QuestionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CensusSuportToolBackendAplication.question')),
                ('SchemaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CensusSuportToolBackendAplication.memberschema')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CensusSuportToolBackendAplication.question')),
            ],
        ),
        migrations.CreateModel(
            name='SchemaField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SchemaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CensusSuportToolBackendAplication.memberschema')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CensusSuportToolBackendAplication.field')),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('FieldId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CensusSuportToolBackendAplication.field')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('communities', models.ManyToManyField(to='CensusSuportToolBackendAplication.community')),
            ],
        ),
        migrations.AddField(
            model_name='form',
            name='volunteer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CensusSuportToolBackendAplication.volunteer'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='CensusRecord',
        ),
        migrations.DeleteModel(
            name='CensusResponse',
        ),
        migrations.DeleteModel(
            name='CensusTemplate',
        ),
        migrations.DeleteModel(
            name='PermissionRequest',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
